// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404/index.vue')['default']
    AdminLayout: typeof import('./src/views/Layout/AdminLayout.vue')['default']
    App: typeof import('./src/App.vue')['default']
    BaseLayout: typeof import('./src/views/Layout/BaseLayout.vue')['default']
    Contest: typeof import('./src/views/Contest/index.vue')['default']
    ContestList: typeof import('./src/views/ContestList/index.vue')['default']
    Detail: typeof import('./src/views/Admin/Contest/Detail/index.vue')['default']
    ForgetPassword: typeof import('./src/views/ForgetPassword/index.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    Login: typeof import('./src/views/Login/Login.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    Problem: typeof import('./src/views/Problem/index.vue')['default']
    ProblemList: typeof import('./src/views/ProblemList/index.vue')['default']
    Register: typeof import('./src/views/Register/index.vue')['default']
    Statistics: typeof import('./src/views/Admin/Statistics/index.vue')['default']
    Status: typeof import('./src/views/Status/index.vue')['default']
    SubmitList: typeof import('./src/components/SubmitList/index.vue')['default']
    SubmitResult: typeof import('./src/components/SubmitResult/index.vue')['default']
    User: typeof import('./src/views/Admin/User/index.vue')['default']
  }
}

export { }
