// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404/index.vue')['default'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    App: typeof import('./src/App.vue')['default'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ATable: typeof import('ant-design-vue/es')['Table'];
    ATag: typeof import('ant-design-vue/es')['Tag'];
    Contest: typeof import('./src/views/Contest/index.vue')['default'];
    ContestList: typeof import('./src/views/ContestList/index.vue')['default'];
    Home: typeof import('./src/views/Home/index.vue')['default'];
    Login: typeof import('./src/views/Login/Login.vue')['default'];
    Problem: typeof import('./src/views/Problem/index.vue')['default'];
    ProblemList: typeof import('./src/views/ProblemList/index.vue')['default'];
  }
}

export {};
